# Generated by Django 2.2.2 on 2019-08-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_auto_20190822_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_of_birth',
        ),
    ]
