# Generated by Django 2.2.2 on 2019-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_auto_20190910_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
