# Generated by Django 2.2.2 on 2019-09-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_auto_20190910_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.Year'),
        ),
    ]
