# Generated by Django 2.2.2 on 2019-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0013_music_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
