# Generated by Django 2.2.2 on 2019-09-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0021_auto_20190911_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.Artist')),
            ],
        ),
    ]
