# Generated by Django 2.2.2 on 2019-09-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0022_popularartist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularartist',
            old_name='artist_id',
            new_name='artist_name',
        ),
    ]
