# Generated by Django 2.2.2 on 2019-09-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0023_auto_20190911_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularartist',
            name='artist_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.Artist'),
        ),
    ]
