# Generated by Django 2.2.2 on 2019-09-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0024_auto_20190911_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularArtist',
        ),
    ]
