# Generated by Django 2.2.2 on 2019-09-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0025_delete_popularartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularArtist',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music.Artist')),
                ('title', models.CharField(blank=True, default='Poupular', max_length=100, null=True)),
            ],
            bases=('Music.artist',),
        ),
    ]
