# Generated by Django 2.2.2 on 2019-09-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0026_popularartist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularArtist',
        ),
    ]
