# Generated by Django 2.2.2 on 2019-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0027_delete_popularartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Poupular', max_length=100, null=True)),
            ],
        ),
    ]
