# Generated by Django 2.2.2 on 2019-09-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0028_popularartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.PopularArtist'),
        ),
    ]
