# Generated by Django 2.2.2 on 2019-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0029_artist_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
