# Generated by Django 2.2.2 on 2019-09-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0031_album_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
