# Generated by Django 2.2.2 on 2019-09-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190913_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
