# Generated by Django 2.2.2 on 2019-09-14 00:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_hashtag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.image_upload),
        ),
    ]
