# Generated by Django 2.2.5 on 2019-10-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190914_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
