# Generated by Django 2.2.6 on 2019-10-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191006_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
